### ISSUE TITLE
Too high CPU usages

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain-agent#7]
The below screenshot is from t2.micro (corgi1 machine)

![image](https://user-images.githubusercontent.com/9711879/46843496-0b584b80-ce0e-11e8-868f-e3e00e8274cc.png)

**Comment by majecty** [comment]
I profiled the Agent using the method from this [link](https://gist.github.com/dlaehnemann/df31787c41bd50c0fe223df07cf6eb89)

Here is the profiled result.

[agent_cpu_usage.zip](https://github.com/CodeChain-io/codechain-agent/files/2528853/agent_cpu_usage.zip)
![2018-10-30 6 13 32](https://user-images.githubusercontent.com/709900/47707583-90958a00-dc6f-11e8-9f1d-5ea5a4c07d2d.png)

The agent takes most of the time to get CPU usage.

**Comment by majecty** [comment]
This issue is fixed.
I made the Agent not to use sysinfo to get memory usage.
I made the Agent not to create HTTP client every RPC request.
